<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>

<div class="row">
    <div class="col-md-10 text-center">
        <?php foreach ($records as $record): ?>
        <h5><?php echo $record->getName(); ?></h5>
        <?php endforeach; ?>
        
        <?php // add at the end of the file after the table
        echo $this->paginationControl(
            // the paginator object
            $this->records,
            // the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
            'sliding',
            // the partial to use to render the control
            array('partial/paginator.phtml', 'Post'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'cmspost'
            )
        );
        ?>
    </div>
</div>