<?php echo $this->doctype(); ?>

<html lang="en">
    <?php echo $this->render('layout/head.phtml'); ?>
    <body>
        <?php echo $this->render('layout/cms.menu.phtml'); ?>
        <div class="container">
            <div class="row border">
                <div class="col-md-3">               
                    <ul>
                        <li>
                            Add New Post
                        </li>
                    </ul>
                </div>
                <div class="col-md-9">
                    <?php echo $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
