<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<table>
    <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Text</th>
    </tr>
    <tr>
        <td><?php echo $name; ?></td>
        <td><?php echo $address; ?></td>
        <td><?php echo $text; ?></td>
    </tr>
</table>