<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
     <div class="container">
         <div class="navbar-header">
             <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
                 <span class="icon-bar"></span>
             </button>
             <a class="navbar-brand" href="<?php echo $this->url('cmsadmin') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Content Management System') ?></a>
         </div>
         <div class="collapse navbar-collapse">
             <ul class="nav navbar-nav">
                 <li class=""><a href="<?php echo $this->url('cmsadmin') ?>"><?php echo $this->translate('Home') ?></a></li>
                 <li class=""><a href="<?php echo $this->url('cmspost') ?>"><?php echo $this->translate('Post') ?></a></li>
                 <li class=""><a href="<?php echo $this->url('home') ?>" target="_blank"><?php echo $this->translate('View Website') ?></a></li>
             </ul>
         </div><!--/.nav-collapse -->
     </div>
 </nav>
