<?php echo $this->doctype(); ?>

<html lang="en">
    <?php echo $this->render('layout/head.phtml'); ?>
    <body>
        <?php echo $this->render('layout/menu.phtml'); ?>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
