<div class="row">
    <div class="col-md-8">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">I'm exploring the world of OPEN SOURCE (PHP & Zend Framework)</h3>
            </div>
            <div class="panel-body">
                <p class="text-center">
                    <img style=“max-width:300px” src="<?php echo $this->basePath(); ?>/img/michael_favila.jpg" class="col-md-4"/>
                </p>
                <p class="text-justify">
                    Hey. Great to see you here. Welcome to my Digital World. Please feel free to roam around.
                    
                    All of my notes and some useful stuff can be found here. Specially in PHP with Zend Framework. Enjoy and happy coding!
                </p>
                <p class="text-justify">
                    My name is Michael Favila, currently a Software Engineer / Web Programmer
                    in Peter Knipp Holdings, where i develop website applications.
                    I'm also a freelancer, a DJ, and an amateur photographer.
                </p>
                <p class=text-justify"">
                    I hold a Bachelor of Science Degree in Computer Science from System
                    Technology Institute (STI). I started programming in 2009 with .NET Framework
                    (C#, VB6, ASP.NET) and JAVA. Then in 2010, PHP became my tool of choice and started
                    using Zend Framework in 2011.
                </p>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">My Recent Notes </h3>
            </div>
            <div class="panel-body">        
                <ul class="list-group">
                    <?php
                    $index = 0;
                    foreach ($records as $record): ?>
                    <li class="list-group-item">
                        <?php echo $record ?>
                      </a>
                    </li>
                    <?php endforeach; ?>
                </ul>                
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Social Media</h3>
            </div>
            <div class="panel-body">
                <!--<a href="http://modules.zendframework.com/" target="_blank">
                    <img src="<?php echo $this->basePath(); ?>/img/zf2-module.png" class="img-responsive"/>
                </a>-->
            <a class="twitter-timeline" href="https://twitter.com/michaelmkp" data-widget-id="376670346385948672">Tweets by @michaelmkp</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">User Experience Design</h3>
            </div>
            <div class="panel-body">
                <div class="video-container">
                    <iframe width="560" height="315" src="//www.youtube.com/embed/OMw1-dHxsTE" frameborder="0" allowfullscreen></iframe>             
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">PHP Frameworks Day - Rasmus Lerdorf</h3>
            </div>
            <div class="panel-body">
                <div class="video-container">
                    <iframe width="420" height="315" src="//www.youtube.com/embed/anr7DQnMMs0" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </div>
    </div>
</div>
